# Generated by Django 3.0.7 on 2020-06-26 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200626_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 17, 39, 36, 821333, tzinfo=utc)),
        ),
    ]
